language: python
python: 
  - "2.7"
  - "3.5"

services: 
  - docker

install:
  - docker build -t capstone:latest .
  - docker run -p 5000:5000 capstone:latest

script: 
  - docker ps | grep -q capstone