version: '2'
services:
  borrel_database:
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
  borrel_flask:
    build:
      context: .
      dockerfile: ./src/flaskapp/Dockerfile
    ports:
      - '8080:8080'
    expose:
      - 8080
    depends_on:
      - borrel_database
    volumes:
      - app-volume:/cache/
  borrel_jukebox:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - borrel_database
    volumes:
      - app-volume:/cache/
volumes:
     app-volume: