name: borrelai
channels:
  - defaults
  - conda-forge
dependencies:
  - apscheduler=3.6.0
  - flask=1.0.2
  - flask-basicauth=0.2.0
  - flask-sqlalchemy=2.3.2
  - pip=19.1
  - python=3.7.3
  - python-dotenv=0.10.1
  - sqlalchemy=1.3.3
  - sqlite=3.28.0
  - pip:
    - spotipy==2.4.4
   
