name: borrelai
channels:
  - defaults
  - conda-forge
dependencies:
  - apscheduler=3.6.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - click=7.0
  - flask=1.0.2
  - flask-basicauth=0.2.0
  - flask-sqlalchemy=2.3.2
  - itsdangerous=1.1.0
  - jinja2=2.10.1
  - krb5=1.16.1
  - libpq=11.2
  - markupsafe=1.1.1
  - openssl=1.1.1b
  - pip=19.1
  - psycopg2=2.7.6.1
  - python=3.7.3
  - python-dotenv=0.10.1
  - pytz=2019.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlalchemy=1.3.3
  - sqlite=3.28.0
  - tk=8.6.8
  - tzlocal=1.5.1
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - werkzeug=0.15.2
  - wheel=0.33.1
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - chardet==3.0.4
    - idna==2.8
    - requests==2.21.0
    - spotipy==2.4.4
    - tinytag==1.2.2
    - urllib3==1.24.2

